rluaux86asmver = "RLuau-x86ASM-v0.0.1nightly"
--[[
THIS IS A NIGHTLY RELEASE BEWARE OF BUGS!!!!
]]

--[[
This is a proof of concept, don't even use this.
It's not finished and will throw errors.
]]

--[[
In order for this to work, make a folder where the emulation scripts are located and name it "registers", its CASE-SENSITIVE.
Next add 4 IntValues, name them "eax", "ebx", "ecx", "edx", also case-sensitive
Make sure all values are 0.
Now feel free to run the script and test it out.
]]

--[[
This is a fun project for x86 MASM Win32 / NASM Win32 Assembly emulation on Roblox.
Keep in mind this only supports x86 MASM Win32 / NASM Assembly 
(unless we'll add GNU Assembly support in the future..)
- Marpl- (WellRoundedMarpl / Nguyễn Trung Chính)
]]