rluaux86asmver = "RLuau-x86ASM-v0.0.1nightly"
--[[
Đây là phiên bản nightly, Có thể lỗi.
]]

--[[
Đây là một phiên bản chứng minh có thể làm được thôi, đừng dùng phiên bản này.
]]

--[[
Để trình giả lập có thể họat động được, làm một thư mục đúng chỗ mà các script giả lập ở đó và đổi tên là "registers", đúng viết thường
của nó.
Đặt 4 NumberValue và đặt tên từng cái là "eax", "ebx", "ecx", "edx", nhớ đặt đúng chữ thường.
Các value này phải là 0.
Bây giờ bạn có thể chạy script và thử nghiệm.
]]

--[[
Đây là một dự án vui cho Roblox có thể giả lập x86 MASM Win32 / NASM Assembly.
Lưu ý là đây chỉ hỗ trợ x86 MASM Win32 / NASM Assembly 
(trừ khi mình sẽ thêm cú pháp của GNU Assembly trong tương lai tới)

- Marpl- (WellRoundedMarpl / Nguyễn Trung Chính)
]]